# 强化学习实验
安装gym和pygame，书上说0.26版本及以后的有不匹配的问题

In [3]:
! pip install gym==0.25.2
! pip install pygame

Defaulting to user installation because normal site-packages is not writeable
Defaulting to user installation because normal site-packages is not writeable
   ---------------------------------------- 0.0/10.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/10.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/10.6 MB 435.7 kB/s eta 0:00:25
   ---------------------------------------- 0.0/10.6 MB 435.7 kB/s eta 0:00:25
   ---------------------------------------- 0.0/10.6 MB 245.8 kB/s eta 0:00:44
   ---------------------------------------- 0.1/10.6 MB 252.2 kB/s eta 0:00:42
   ---------------------------------------- 0.1/10.6 MB 327.3 kB/s eta 0:00:33
   ---------------------------------------- 0.1/10.6 MB 385.0 kB/s eta 0:00:28
   ---------------------------------------- 0.1/10.6 MB 385.0 kB/s eta 0:00:28
   ---------------------------------------- 0.1/10.6 MB 385.0 kB/s eta 0:00:28
   ---------------------------------------- 0.1/10.6 MB 385.0 kB/s eta 0

In [19]:
!pip install glfw
!pip install mujoco

Defaulting to user installation because normal site-packages is not writeable
Defaulting to user installation because normal site-packages is not writeable
     ---------------------------------------- 0.0/45.4 kB ? eta -:--:--
     ---------------------------------------- 0.0/45.4 kB ? eta -:--:--
     --------- ------------------------------ 10.2/45.4 kB ? eta -:--:--
     ----------------- -------------------- 20.5/45.4 kB 217.9 kB/s eta 0:00:01
     ----------------- -------------------- 20.5/45.4 kB 217.9 kB/s eta 0:00:01
     ------------------------- ------------ 30.7/45.4 kB 131.3 kB/s eta 0:00:01
     -------------------------------------- 45.4/45.4 kB 188.0 kB/s eta 0:00:00
  Using cached absl_py-2.1.0-py3-none-any.whl.metadata (2.3 kB)
  Using cached PyOpenGL-3.1.7-py3-none-any.whl.metadata (3.2 kB)
   ---------------------------------------- 0.0/4.7 MB ? eta -:--:--
   ---------------------------------------- 0.0/4.7 MB ? eta -:--:--
   -------------------------------------

### 注:部分实验环境需要mujoco，配置上我没看完
下面的代码不需要mujoco，不需要运行上面的安装

In [25]:
import gym # 导入 Gym 的 Python 接口环境包
env = gym.make('CartPole-v0') # 构建实验环境
env.reset() # 重置一个回合
for _ in range(1000):
    env.render()
    action = env.action_space.sample()
    observation, reward, done, info = env.step(action)
    print(observation)
env.close()



[-0.00588768 -0.1904368   0.02772638  0.25959814]
[-0.00969642 -0.38594335  0.03291834  0.5608958 ]
[-0.01741528 -0.5815115   0.04413626  0.86376524]
[-0.02904551 -0.38701725  0.06141156  0.5852799 ]
[-0.03678586 -0.19280684  0.07311716  0.31255707]
[-0.04064199 -0.38889015  0.0793683   0.62737346]
[-0.0484198  -0.19496043  0.09191577  0.36070442]
[-0.05231901 -0.3912605   0.09912986  0.6808968 ]
[-0.06014422 -0.58760935  0.1127478   1.0030706 ]
[-0.0718964  -0.78404224  0.1328092   1.3289268 ]
[-0.08757725 -0.5908224   0.15938774  1.0805805 ]
[-0.0993937  -0.7876481   0.18099935  1.4187387 ]
[-0.11514666 -0.9844893   0.20937413  1.7621009 ]
[-0.13483645 -0.7922611   0.24461614  1.5411628 ]
[-0.15068166 -0.9893459   0.2754394   1.8991914 ]
[-0.17046858 -0.79805565  0.31342322  1.703031  ]
[-0.1864297  -0.9951407   0.34748384  2.0749018 ]
[-0.2063325  -0.8047953   0.38898188  1.9065652 ]
[-0.22242841 -0.6153548   0.42711318  1.7551309 ]
[-0.2347355  -0.81216776  0.4622158   2.1456175 ]


In [13]:
from gym import envs
#这个是打印环境的代码，我用上面的代码试了一部分环境，蚂蚁和一些难的场景需要mujoco
env_specs = envs.registry.values() 
envs_ids = [env_spec.id for env_spec in env_specs]
print(envs_ids)


['CartPole-v0', 'CartPole-v1', 'MountainCar-v0', 'MountainCarContinuous-v0', 'Pendulum-v1', 'Acrobot-v1', 'LunarLander-v2', 'LunarLanderContinuous-v2', 'BipedalWalker-v3', 'BipedalWalkerHardcore-v3', 'CarRacing-v2', 'Blackjack-v1', 'FrozenLake-v1', 'FrozenLake8x8-v1', 'CliffWalking-v0', 'Taxi-v3', 'Reacher-v2', 'Reacher-v4', 'Pusher-v2', 'Pusher-v4', 'InvertedPendulum-v2', 'InvertedPendulum-v4', 'InvertedDoublePendulum-v2', 'InvertedDoublePendulum-v4', 'HalfCheetah-v2', 'HalfCheetah-v3', 'HalfCheetah-v4', 'Hopper-v2', 'Hopper-v3', 'Hopper-v4', 'Swimmer-v2', 'Swimmer-v3', 'Swimmer-v4', 'Walker2d-v2', 'Walker2d-v3', 'Walker2d-v4', 'Ant-v2', 'Ant-v3', 'Ant-v4', 'Humanoid-v2', 'Humanoid-v3', 'Humanoid-v4', 'HumanoidStandup-v2', 'HumanoidStandup-v4']


### 小车上山
先看各个空间都有什么

注：下面的代码每次运行要从这里开始

In [41]:
import gym
env = gym.make('MountainCar-v0')
print('观测空间 = {}'. format(env.observation_space))
print('动作空间 = {}'. format(env.action_space))
print('观测范围 = {} ~ {}'. format(env.observation_space.low,
env.observation_space.high))
print('动作数 = {}'. format(env.action_space.n))


观测空间 = Box([-1.2  -0.07], [0.6  0.07], (2,), float32)
动作空间 = Discrete(3)
观测范围 = [-1.2  -0.07] ~ [0.6  0.07]
动作数 = 3


In [42]:
class SimpleAgent:
    def __init__(self, env):
        # 初始化，接收环境参数
        self.env = env

    def decide(self, observation):
        """
        根据观察值决策动作。
        :param observation: 包括位置 (position) 和速度 (velocity)
        :return: 动作 (action)
        """
        position, velocity = observation
        # 定义速度的下界和上界
        lb = min(-0.09 * (position + 0.25) ** 2 + 0.03,
                 0.3 * (position + 0.9) ** 4 - 0.008)
        ub = -0.07 * (position + 0.38) ** 2 + 0.07

        # 根据速度是否在范围内选择动作
        if lb < velocity < ub:
            action = 2  # 推动方向
        else:
            action = 0  # 静止或另一个方向
        return action

    def learn(self, *args):
        """
        学习方法，占位函数。不包含学习的方法，只有决策，所以不是RL的Agent
        """
        pass

# 使用环境初始化智能体
agent = SimpleAgent(env)


In [43]:
def play(env, agent, render=False, train=False):
    """
    运行一回合游戏。
    :param env: 游戏环境
    :param agent: 智能体
    :param render: 是否渲染图形界面，默认为 False
    :param train: 是否训练智能体，默认为 False
    :return: 本回合的总奖励
    """
    # 初始化回合总奖励
    episode_reward = 0.0

    # 重置环境，获取初始观察值
    observation = env.reset()

    while True:
        # 渲染游戏界面
        if render:
            env.render()

        # 智能体决策动作
        action = agent.decide(observation)

        # 执行动作，获取下一状态、奖励以及是否结束
        next_observation, reward, done, _ = env.step(action)

        # 累计奖励
        episode_reward += reward

        # 如果训练模式开启，智能体进行学习
        if train:
            agent.learn(observation, action, reward, done)

        # 如果回合结束，退出循环
        if done:
            break

        # 更新当前观察值
        observation = next_observation

    # 返回本回合的总奖励
    return episode_reward


In [44]:
env.seed(3) # 设置随机种子，让结果可复现
episode_reward = play(env, agent, render=True)
print('回合奖励 = {}'. format(episode_reward))
env.close() # 关闭图形界面

回合奖励 = -105.0


In [47]:
import numpy as np
episode_rewards = [play(env, agent) for _ in range(100)]
print('平均回合奖励 = {}'. format(np.mean(episode_rewards)))

平均回合奖励 = -105.47
